name: Arnau Esteban, Escola del Treball
markdown: kramdown
permalink: /experiencia/:year/:month/:day/:title
email: arnauesteban@hotmail.com
baseurl: "" 
url: "http://isx47590131.github.io" 
github_username: isx47590131


